/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.Conexao;
import dao.DominioDto;
import dao.IConexao;
import dao.IDominio;
import dao.IUsuarioDto;
import dao.UsuarioDto;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Vector;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import model.SexoModel;
import model.UsuarioAlterarModel;
import model.UsuarioInserirModel;
import model.UsuarioModel;

/**
 *
 * @author joaov
 */
public class AlteracaoTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlteracaoTela.class.getName());
    private IDominio dominioDto ;
    private IUsuarioDto usuarioDto;
    private MainTela mainTela;
    private UsuarioModel usuario;
    /**
     * Creates new form CadastroTela
     */
    
    public AlteracaoTela() {
        initComponents();
    }
        
    public AlteracaoTela(MainTela mainTela,String CPF) {
        initComponents();
        IConexao sqlLite = new Conexao();
        this.usuarioDto = new UsuarioDto(sqlLite);
        this.usuario = this.usuarioDto.PesquisarUsuarioPorCPF(CPF);
        this.dominioDto = new DominioDto(sqlLite);
        this.SexoCombo();
        this.CarregarCampos();
        this.mainTela = mainTela;
    }
    
    public void CarregarCampos()
    {
        System.out.println(this.usuario.getNome());
        this.textNome.setText(this.usuario.getNome());
        this.textEmail.setText(this.usuario.getEmail());
        this.textTelefone.setText(this.usuario.getTelefone());
        this.textDataNascimento.setText(this.usuario.getDataNascimento());
    }
    
    
    public void SexoCombo()
    {
        
        var listaSexo = dominioDto.BuscarSexo();
        //comboSexo.removeAllItems();
        for(SexoModel sexo : listaSexo)
        {
            comboSexo.addItem(sexo.getDescricao());
        }
        comboSexo.setSelectedIndex(this.usuario.getSexo() - 1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        textEmail = new javax.swing.JTextField();
        textEmail.setForeground(java.awt.Color.BLACK);
        textDataNascimento = new javax.swing.JFormattedTextField(Mascara("##/##/####"));
        jButton1 = new javax.swing.JButton();
        comboSexo = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        textTelefone = new javax.swing.JFormattedTextField(Mascara("## #####-####"));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Alterar informação do cliente");

        textNome.setForeground(java.awt.Color.gray);
        textNome.setText("Nome");
        textNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textNomeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textNomeFocusLost(evt);
            }
        });
        textNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textNomeMouseClicked(evt);
            }
        });
        textNome.addActionListener(this::textNomeActionPerformed);

        textEmail.setText("Email");
        textEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textEmailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textEmailFocusLost(evt);
            }
        });
        textEmail.addActionListener(this::textEmailActionPerformed);

        textDataNascimento.setText("Data de nascimento");
        textDataNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textDataNascimentoFocusLost(evt);
            }
        });
        textDataNascimento.addActionListener(this::textDataNascimentoActionPerformed);

        jButton1.setText("Alterar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        comboSexo.setModel(new javax.swing.DefaultComboBoxModel<>());
        comboSexo.addActionListener(this::comboSexoActionPerformed);

        jButton2.setText("Cancelar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        textTelefone.setText("Telefone");
        textTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textTelefoneFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                textTelefoneFocusLost(evt);
            }
        });
        textTelefone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textTelefoneMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(148, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE))
                .addGap(143, 143, 143))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textTelefone)
                    .addComponent(textEmail, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textNome)
                    .addComponent(textDataNascimento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                    .addComponent(comboSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(textEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap())
        );

        textNome.setForeground(Color.BLACK);
        textNome.setToolTipText("Nome");
        textEmail.setToolTipText("Email");
        textTelefone.setForeground(Color.BLACK);
        textTelefone.setToolTipText("Telefone");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeActionPerformed

    private void textEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailActionPerformed

    private void textDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textDataNascimentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        alterarUsuario();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void comboSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboSexoActionPerformed

    private void textNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textNomeFocusGained

    private void textNomeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textNomeFocusLost
        // TODO add your handling code here:
        if (textNome.getText().isEmpty()) { 
            textNome.setText(this.usuario.getNome());
        }
        
    }//GEN-LAST:event_textNomeFocusLost

    private void textNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textNomeMouseClicked
        // TODO add your handling code here: // volta placeholder }
    }//GEN-LAST:event_textNomeMouseClicked

    private void textEmailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textEmailFocusGained

    private void textEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textEmailFocusLost
        // TODO add your handling code here:
        if(textEmail.getText().isEmpty()) {
            textEmail.setText(this.usuario.getEmail());
        }
    }//GEN-LAST:event_textEmailFocusLost

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.FecharTela();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textTelefoneFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTelefoneFocusGained
        // TODO add your handling code here:
        if (textTelefone.getText().isEmpty()) { 
            textTelefone.setText("Telefone");
            textTelefone.setForeground(Color.GRAY);// volta placeholder }
        }else {
            textTelefone.setForeground(Color.BLACK);
        }
    }//GEN-LAST:event_textTelefoneFocusGained

    private void textTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textTelefoneFocusLost
        // TODO add your handling code here:
        if(textTelefone.getText().isEmpty()) {
            textTelefone.setText(this.usuario.getTelefone());

        }
    }//GEN-LAST:event_textTelefoneFocusLost

    private void textTelefoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textTelefoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_textTelefoneMouseClicked

    private void textDataNascimentoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textDataNascimentoFocusLost
        // TODO add your handling code here:
        System.out.println(textDataNascimento.getText().replace("/", ""));
        if(textDataNascimento.getText().replace("/", "").isBlank()){
            textDataNascimento.setText(this.usuario.getDataNascimento());
        }
    }//GEN-LAST:event_textDataNascimentoFocusLost
    
    private void alterarUsuario() {
        String nome = textNome.getText();
        String email = textEmail.getText();
        String telefone = textTelefone.getText();
        int sexo = comboSexo.getSelectedIndex();
        String dataNasc = textDataNascimento.getText();
        System.out.println(nome);
        var usuarioaAlterar = new UsuarioAlterarModel(this.usuario.getIdUsuario(), nome, email, telefone, sexo +1, dataNasc);
        
        usuarioDto.AlterarUsuario(usuarioaAlterar);
        this.mainTela.LoadTabelaUsuario();
        this.dispose();

    }
    
    public MaskFormatter Mascara(String Mascara){
        
        MaskFormatter F_Mascara = new MaskFormatter();
        try{
            F_Mascara.setMask(Mascara); //Atribui a mascara
            F_Mascara.setPlaceholderCharacter(' '); //Caracter para preencimento 
        }
        catch (ParseException excecao) {
        excecao.printStackTrace();
        } 
        return F_Mascara;
    }
    
    public void FecharTela() {
        this.dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlteracaoTela().setVisible(true));
    }
    
     

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> comboSexo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField textDataNascimento;
    private javax.swing.JTextField textEmail;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables
}
